// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4gXgNl9NC6pm32BLoUkVo1TqJaGAIe7E',
    appId: '1:670063203144:web:5bc52343bd5ce10b54597d',
    messagingSenderId: '670063203144',
    projectId: 'serkappupdate',
    authDomain: 'serkappupdate.firebaseapp.com',
    storageBucket: 'serkappupdate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFS6jPhbJ_sWHHrh6WjwBDcOBbsNwcqB8',
    appId: '1:670063203144:android:b29f4248e5b30e4054597d',
    messagingSenderId: '670063203144',
    projectId: 'serkappupdate',
    storageBucket: 'serkappupdate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hM2xQCOMh2JKOU7QS52Lj7OpZFhPHfU',
    appId: '1:670063203144:ios:1e02d30a49b1b4f454597d',
    messagingSenderId: '670063203144',
    projectId: 'serkappupdate',
    storageBucket: 'serkappupdate.firebasestorage.app',
    iosBundleId: 'com.example.serkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6hM2xQCOMh2JKOU7QS52Lj7OpZFhPHfU',
    appId: '1:670063203144:ios:1e02d30a49b1b4f454597d',
    messagingSenderId: '670063203144',
    projectId: 'serkappupdate',
    storageBucket: 'serkappupdate.firebasestorage.app',
    iosBundleId: 'com.example.serkapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4gXgNl9NC6pm32BLoUkVo1TqJaGAIe7E',
    appId: '1:670063203144:web:a1b997d162c1943154597d',
    messagingSenderId: '670063203144',
    projectId: 'serkappupdate',
    authDomain: 'serkappupdate.firebaseapp.com',
    storageBucket: 'serkappupdate.firebasestorage.app',
  );
}
