// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwovUGdWkZb1JeX4l3ZQRRT07A84B0ouM',
    appId: '1:717006875381:web:9bfd1c32a83eb5401733bc',
    messagingSenderId: '717006875381',
    projectId: 'serkapp-c1d85',
    authDomain: 'serkapp-c1d85.firebaseapp.com',
    storageBucket: 'serkapp-c1d85.firebasestorage.app',
    measurementId: 'G-QPH575NPE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwBz1NNgXTFJzZfZnSWsFatfHUUqxB3zo',
    appId: '1:717006875381:android:853f8189ec2754561733bc',
    messagingSenderId: '717006875381',
    projectId: 'serkapp-c1d85',
    storageBucket: 'serkapp-c1d85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqjK8l89n6jhbimquP2TRSEX1zSFigHPY',
    appId: '1:717006875381:ios:1961a5e7c5e583d61733bc',
    messagingSenderId: '717006875381',
    projectId: 'serkapp-c1d85',
    storageBucket: 'serkapp-c1d85.firebasestorage.app',
    iosBundleId: 'com.example.serkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqjK8l89n6jhbimquP2TRSEX1zSFigHPY',
    appId: '1:717006875381:ios:1961a5e7c5e583d61733bc',
    messagingSenderId: '717006875381',
    projectId: 'serkapp-c1d85',
    storageBucket: 'serkapp-c1d85.firebasestorage.app',
    iosBundleId: 'com.example.serkapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwovUGdWkZb1JeX4l3ZQRRT07A84B0ouM',
    appId: '1:717006875381:web:2b7a809bda1368621733bc',
    messagingSenderId: '717006875381',
    projectId: 'serkapp-c1d85',
    authDomain: 'serkapp-c1d85.firebaseapp.com',
    storageBucket: 'serkapp-c1d85.firebasestorage.app',
    measurementId: 'G-B73XK7VT3P',
  );
}
